source 'https://rubygems.org'

gem 'rails', '2.3.5'
gem 'mysql', '2.9.1'
gem 'mysql2', '0.3.17'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '~> 2.0'
gem 'settingslogic', '2.0.9'                                                             
gem 'fastercsv', '1.5.5'                                                     
gem 'rest-client', '1.6.7'                                                               
gem 'nokogiri', '1.5.0'
gem 'mechanize', '2.7.0'                                                                 
gem 'json', '1.5.0'
gem 'rake',  '0.8.7'
gem 'bundler'
gem 'activerecord-mysql2-adapter', '0.0.3'
gem 'passenger', '4.0.53'
gem 'rcov', '1.0.0'
gem 'colorize', '0.7.3'
gem 'actionmailer', '2.3.5'
gem 'mime-types', '1.25.1'
gem 'domain_name', '0.5.22'
