site_code : BBC
site_name : Balaka BLM Clinic
ip_address: 127.0.0.1
database : validation_result2
username : pach
password : pachccc123
port : 5984

dashboard_host : 127.0.0.1
dashboard_port : 5984
dashboard_username : pach
dashboard_password : pachccc123
dashboard_database : validation_result
